### ISSUE TITLE
Milestone 02 RVTM Updated

### ISSUE THREAD

**Issue by savannahc502** [LPouliot/Soph-Spring-SYS-265-Final-Project#16]
Probable RVTM topics that will be hit:

- [x] 2) DHCP1 and DHCP2 should provide DHCP services to your LAN. They should also be redundant. Turn off DHCP1 or 2 and ipconfig/release and /renew from W1.
- [x] 3) MGMT2 will be an Ansible controller system that can control your entire domain, with the exception of Windows workstations and the firewall. You should be able to run interactive commands against all these systems.
- [x] 4) Util will be a system that you can provision with a new application via MGMT2 and Ansible. It can also be used to assist in meeting other requirements. Deploy an application that has not been covered in class to util, using an Ansible playbook.
- [x] 5) MGMT1, DC1, DC2, DFS1, DFS2 and your workstations represent your Active Directory Infrastructure. Your domain should be your groupname.local. Join all Windows systems to the domain and at least one of your Linux systems.
- [x] 12) Use Ansible to install a yum package.
