### ISSUE TITLE
Milestone 1 RVTM 

### ISSUE THREAD

**Issue by savannahc502** [LPouliot/Soph-Spring-SYS-265-Final-Project#3]
Requirements Verification Traceability Matrix is updated accordingly

- [x] Matrix is properly created with descriptions - Lily
- [x] Matrix is properly hyperlinked to build Wiki Pages - Sav
- [x] Matrix is properly hyperlinked to test videos for each section - Sav
- [x] Tests are recorded -Sav and Diego
