### ISSUE TITLE
Milestone 01 Video Demo

### ISSUE THREAD

**Issue by savannahc502** [LPouliot/Soph-Spring-SYS-265-Final-Project#7]
Video demonstration for submission on Canvas, showcasing:
- [x]  Routing works (LAN-LAN, LAN-WAN)
- [x] WKS1 and WKS2 are domain joined
- [x] ADDS is redundant
- [x] Reference Network Diagram
- [x] All Team Members present on their GitHub repo portions referencing their features 
- [x] Build RVTM that is in progress for each system
